import test from 'node:test';import assert from 'node:assert/strict';
import {deriveKeys,b64,unb64,encrypt,authorization,validateSubscription} from '../worker/webpush.js';
import {TimerAlarm} from '../worker/index.js';
test('derivação coincide com o vetor oficial RFC 8291, apêndice A',async()=>{
 const {key,nonce}=await deriveKeys(unb64('kyrL1jIIOHEzg3sM2ZWRHDRB62YACZhhSlknJ672kSs'),unb64('BTBZMqHH6r4Tts7J_aSIgg'),unb64('DGv6ra1nlYgDCS1FRnbzlw'),unb64('BCVxsr7N_eNgVRqvHtD0zTZsEc6-VV-JvLexhqUzORcxaOzi6-AYWXvTBHm4bjyPjs7Vd8pZGH6SRpkNtoIAiw4'),unb64('BP4z9KsN6nGRTbVYI_c7VJSPQTBtkgcy27mlmlMoZIIgDll6e3vCYLocInmYWAmS6TlzAC8wEqKK6PBru3jl7A8'));
 assert.equal(b64(key),'oIhVW04MRdy2XN9CiKLxTg');assert.equal(b64(nonce),'4h_95klXJ5E_qnoN');
});
test('mensagem criptografada pode ser aberta pelo receptor e adulteração falha',async()=>{
 const receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const pub=new Uint8Array(await crypto.subtle.exportKey('raw',receiver.publicKey)),auth=crypto.getRandomValues(new Uint8Array(16));
 const packet=await encrypt({keys:{p256dh:b64(pub),auth:b64(auth)}},{expires:123});assert.equal(packet[20],65);assert.equal(new DataView(packet.buffer).getUint32(16),4096);
 const sender=packet.slice(21,86),senderKey=await crypto.subtle.importKey('raw',sender,{name:'ECDH',namedCurve:'P-256'},false,[]),secret=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:senderKey},receiver.privateKey,256));
 const {key,nonce}=await deriveKeys(secret,auth,packet.slice(0,16),pub,sender),aes=await crypto.subtle.importKey('raw',key,'AES-GCM',false,['decrypt']);
 const plaintext=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce},aes,packet.slice(86)));assert.equal(plaintext.at(-1),2);assert.deepEqual(JSON.parse(new TextDecoder().decode(plaintext.slice(0,-1))),{expires:123});
 packet[100]^=1;await assert.rejects(crypto.subtle.decrypt({name:'AES-GCM',iv:nonce},aes,packet.slice(86)));
});
test('VAPID assina audiência e expiração verificáveis',async()=>{const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),priv=await crypto.subtle.exportKey('jwk',keys.privateKey),pub=b64(new Uint8Array(await crypto.subtle.exportKey('raw',keys.publicKey)));const value=await authorization('https://web.push.apple.com/test',priv,pub,'https://example.com');const token=value.match(/t=([^,]+)/)[1],parts=token.split('.'),body=JSON.parse(new TextDecoder().decode(unb64(parts[1])));assert.equal(body.aud,'https://web.push.apple.com');assert.ok(body.exp>Date.now()/1000);assert.equal(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},keys.publicKey,unb64(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1])),true)});
test('rejeita destinos de push que poderiam alcançar servidores arbitrários',()=>{for(const endpoint of ['http://web.push.apple.com/a','https://127.0.0.1/a','https://web.push.apple.com.evil.test/a','https://user@web.push.apple.com/a','https://web.push.apple.com:444/a'])assert.throws(()=>validateSubscription({endpoint,keys:{}}))});
function fixture(){const map=new Map();let alarm;const storage={get:async k=>structuredClone(map.get(k)),put:async(k,v)=>{map.set(k,structuredClone(v))},deleteAll:async()=>map.clear(),setAlarm:async n=>{alarm=n},deleteAlarm:async()=>{alarm=null}};return {map,object:new TimerAlarm({storage},{ENABLED:'false'}),getAlarm:()=>alarm}}
function req(path,value){return new Request('https://internal'+path,{method:'POST',body:JSON.stringify(value)})}
test('agendamento exige token, substitui prazo e cancela sem apagar inscrição',async()=>{const f=fixture(),now=Date.now();await f.object.fetch(req('/init',{tokenHash:'secret',subscription:{}}));assert.equal((await f.object.fetch(req('/schedule',{tokenHash:'wrong',version:1,deadline:now+10000,total:10}))).status,401);assert.equal((await f.object.fetch(req('/schedule',{tokenHash:'secret',version:1,deadline:now+10000,total:10}))).status,200);assert.equal(f.getAlarm(),now+10000);assert.equal((await f.object.fetch(req('/schedule',{tokenHash:'secret',version:1,deadline:now+5000,total:5}))).status,409);await f.object.fetch(req('/schedule',{tokenHash:'secret',version:2,deadline:null,total:0}));assert.equal(f.map.get('record').deadline,null);assert.ok(f.getAlarm()>now+80000000)});
test('remoção autenticada elimina a inscrição e o alarme',async()=>{const f=fixture();await f.object.fetch(req('/init',{tokenHash:'secret',subscription:{}}));await f.object.fetch(req('/remove',{tokenHash:'secret'}));assert.equal(f.map.size,0);assert.equal(f.getAlarm(),null)});
test('prazo excessivo não é aceito',async()=>{const f=fixture();await f.object.fetch(req('/init',{tokenHash:'secret',subscription:{}}));assert.equal((await f.object.fetch(req('/schedule',{tokenHash:'secret',version:1,deadline:Date.now()+700000,total:700}))).status,400)});
